# Generated by Django 3.1.1 on 2020-09-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200916_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
