# Generated by Django 3.1.1 on 2020-09-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200916_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='main.item'),
        ),
    ]
