# Generated by Django 3.1.1 on 2020-09-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_offer_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fourth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='main.item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='main.item'),
        ),
    ]
