# Generated by Django 3.1.1 on 2020-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.CharField(choices=[('1', 'Da.'), ('2', 'Ne.')], default='1', max_length=20),
        ),
    ]
