# Generated by Django 3.1.1 on 2020-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200920_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
