# Generated by Django 3.1.1 on 2020-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200920_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lager',
            field=models.CharField(max_length=100),
        ),
    ]
