# Generated by Django 3.1.1 on 2020-09-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='question',
            new_name='message',
        ),
    ]
