# Generated by Django 3.1.1 on 2020-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200921_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sendEmail',
            field=models.BooleanField(default=False),
        ),
    ]
